### ISSUE TITLE
Unsupported layers found IECore OpenVINO MYRIAD

### ISSUE THREAD

**Issue by Omar-AE** [mmphego/face_mask_detection_openvino#1] opened 2020-06-18 13:11 UTC
Everything works perfectly when I run the following on cpu, but when I choose MYRIAD: `--device 'MYRIAD'`, the following exception is raised:

```

~/mask-openvino/face_mask_detection_openvino$ python3 main.py     --face-model models/face-detection-adas-0001.xml     --mask-model models/face_mask.xml     --debug     -i resources/mask.mp4 --device 'MYRIAD'
Traceback (most recent call last):
  File "main.py", line 221, in <module>
    infer_on_stream(args)
  File "main.py", line 137, in infer_on_stream
    device=args.device,
  File "/home/nvr/mask-openvino/face_mask_detection_openvino/inference.py", line 72, in load_model
    raise RuntimeError(msg)
RuntimeError: Unsupported layers found: ['data'], Check whether extensions are available to add to IECore.

```

I am using:
ubuntu 18 LTS
Python 3.6.9

I would appreciate a quick help for this.

**Comment by mmphego** [comment] 2020-06-18 15:22
I never tested the code with the NCS2 but you can try commenting out these lines: https://github.com/mmphego/face_mask_detection_openvino/blob/master/inference.py#L60+L72 

Also, you might want to try a lower precision model FP16. Not sure if the NCS2 support the heterogenous plugin...

Try: `--device HETERO:MYRIAD,CPU` 

Goodluck

**Comment by Omar-AE** [comment] 2020-06-18 16:26
I tried your suggestions.
Now I am getting the following exception:

```

~/mask-openvino/face_mask_detection_openvino$ python3 main.py     --face-model models/face-detection-adas-0001.xml     --mask-model models/face_mask.xml     --debug     -i resources/mask.mp4
Traceback (most recent call last):
  File "main.py", line 221, in <module>
    infer_on_stream(args)
  File "main.py", line 141, in infer_on_stream
    device=args.device,
  File "/home/nvr/mask-openvino/face_mask_detection_openvino/inference.py", line 56, in load_model
    network=self.network, device_name=device
  File "ie_api.pyx", line 178, in openvino.inference_engine.ie_api.IECore.load_network
  File "ie_api.pyx", line 187, in openvino.inference_engine.ie_api.IECore.load_network
RuntimeError: Can not init Myriad device: NC_ERROR

```

**Comment by mmphego** [comment] 2020-06-20 01:54
Few minutes on Google led me here:
- https://software.intel.com/en-us/forums/intel-distribution-of-openvino-toolkit/topic/844287
- https://software.intel.com/en-us/node/821098
- https://forums.intel.com/s/question/0D50P00004Pa9ODSAZ/i-am-interested-in-knowing-if-anyone-has-setup-openvino-for-neural-compute-stick-2-either-in-windows-10-or-linux-os

**Comment by mmphego** [comment] 2020-06-22 12:13
Cannot reproduce therefore closing issue.

**Closed as completed by mmphego** 2020-06-22 12:13 UTC
